### ISSUE TITLE
make format_datetime the default behavior ?

### ISSUE THREAD

**Issue by sbcgua** [sbcgua/ajson#101]
Usual json date format is "YYYY-MM-DD", yet by default ajson keeps the abap formatting (no dashes). This is fixed by the `format_datetime` call at creation time. Though ... maybe it makes sense to make date formatting the default behavior ...

**Comment by mbtools** [comment]
i'm mostly consuming JSON, not creating it but would also say "YYYY-MM-DD" (iso) should be the default

**Comment by sbcgua** [comment]
done. Beware of potential regressions @mbtools @larshp 
will publish as 1.1.5 in a moment
