### ISSUE TITLE
keep_item_order() vs create_from()

### ISSUE THREAD

**Issue by larshp** [sbcgua/ajson#137]
calling create_from() with an existing ajson insance where keep_item_order() is set, returns a new instance where keep_item_order() is not set

I guess create_from() should inherit the keep_item_order from II_SOURCE_JSON?

https://github.com/sbcgua/ajson/blob/5e6278d185a90421ad8f28d4f0c79e00a771b063/src/zcl_ajson.clas.abap#L127-L150

**Comment by sbcgua** [comment]
Yes ... https://github.com/sbcgua/ajson/pull/117/files#diff-b145c7a1905ff4c3124f24af34209abae7721c6ae929b4482e17ab17d20698dcR173

Just need to find time to finish this PR ... or cherrypick the changes

**Comment by larshp** [comment]
@sbcgua did you have time to look into this?

**Comment by sbcgua** [comment]
Not yet. But I'll try to do it this week

**Comment by larshp** [comment]
no worries, first things first

**Comment by sbcgua** [comment]
#117 merged, should work now. BTW note doc changes (deprecation notes at the beginning in particular)

**Comment by sbcgua** [comment]
Can be closed ?
