### ISSUE TITLE
Cloud compatibility

### ISSUE THREAD

**Issue by mbtools** [sbcgua/ajson#147]
I did a quick comparison with https://abapedia.org/ and most of the used standard classes and interfaces are released for ABAP Cloud. However, `cl_abap_codepage` is not released. 

https://github.com/sbcgua/ajson/blob/b40ccfddb39a6124e6ec74d7d3e5202ba4c3ac9b/src/zcl_ajson.clas.locals_imp.abap#L259

Suggestion: replace with `CL_ABAP_CONV_CODEPAGE`.

**Comment by larshp** [comment]
no trivial task with code pages, got some snippets to convert to and from xstring, which works on prem and Steampunk,

https://github.com/open-abap/open-table-maintenance/blob/main/src/zcl_otm_table_maintenance.clas.abap#L360-L389

https://github.com/open-abap/open-table-maintenance/blob/main/src/zcl_otm_table_maintenance.clas.abap#L132-L161

**Comment by sbcgua** [comment]
Yeap, good suggestion. Will have a look

**Comment by sbcgua** [comment]
#148
