### ISSUE TITLE
CX_SXML_ERROR is not released on Steampunk

### ISSUE THREAD

**Issue by larshp** [sbcgua/ajson#153]
see https://abapedia.org/steampunk-2302-api/

any opinion on how to avoid using it?

I probably recommend replacing it with all the
CLAS CX_SXML_ILLEGAL_ARGUMENT_ERROR
CLAS CX_SXML_INTERNAL_ERROR
CLAS CX_SXML_NAME_ERROR
CLAS CX_SXML_PARSE_ERROR
CLAS CX_SXML_STATE_ERROR

instead

**Comment by sbcgua** [comment]
I wouldn't narrow it to specific list. The idea was the opposite. I'd better replace with `cx_dynamic_check` instead. It is just in one place, if I remember well ?
