### ISSUE TITLE
Mapper gets lost after filtering

### ISSUE THREAD

**Issue by oblomov-dev** [sbcgua/ajson#176]
Not sure if this is an intended behaviour, but i was suprised:
```abap
    DATA:
      BEGIN OF ls_test,
        text TYPE string VALUE `ABC`,
      END OF ls_test.

    DATA(test) = zcl_ajson=>create_empty( ii_custom_mapping = zcl_abapgit_ajson_mapping=>create_upper_case( ) ).

    test->set(
        iv_path = `/`
        iv_val  = ls_test ).

    DATA(lv_result) = test->stringify( ). "{"TEXT":"ABC"}

    DATA(test_filtered) = test->filter( zcl_abapgit_ajson_filter_lib=>create_empty_filter( ) ).

    test_filtered->set(
        iv_path = `/`
        iv_val  = ls_test ).

    DATA(lv_result2) = test_filtered->stringify( ). "{"text":"ABC"}

    "expected:  "{"TEXT":"ABC"} -> mapper got lost?
```
The returning object of the filter fucntion does not get the mapping of the original object:
<img width="300" alt="image" src="https://github.com/sbcgua/ajson/assets/102328295/b024857a-1cc8-47a4-9e78-6dd465571117">

But maybe my understanding of the API was just wrong and everything is fine like this.

**Comment by sbcgua** [comment]
Sorry for late response. Well ... looks like a bug on the one hand. But on the other the `ii_custom_mapping` is a deprecated feature - https://github.com/sbcgua/ajson?tab=readme-ov-file#mapping-via-to_abap-and-to_json-deprecated - in favor of `filter` method. So I'd better not rely on this particular feature but use the `filter` approach instead.

**Comment by oblomov-dev** [comment]
ah thank you for the hint, overlooked that this is deprecated, in my specific situation i use now the following APIs and it works as i would expect:
```abap
        DATA(lo_json) =  CAST z2ui5_if_ajson( z2ui5_cl_ajson=>new( ) ).
        lo_json->set( iv_path = `/` iv_val = val ).

        IF config-custom_mapper IS BOUND.
          lo_json = lo_json->map( config-custom_mapper ).
        ELSE.
          lo_json = lo_json->map( z2ui5_cl_ajson_mapping=>create_upper_case( ) ).
        ENDIF.

        IF config-custom_filter IS BOUND.
          lo_json = lo_json->filter( config-custom_filter ).
        ELSE.
          lo_json = lo_json->filter( z2ui5_cl_ajson_filter_lib=>create_empty_filter( ) ).
        ENDIF.
```

**Comment by sbcgua** [comment]
Good to know! So the issue can be closed?

**Comment by oblomov-dev** [comment]
yes thanks for the help!
