### ISSUE TITLE
Parsing JSON with comments (`jsonc`)

### ISSUE THREAD

**Issue by mbtools** [sbcgua/ajson#188]
It would be nice to be able to parse JSON which contains comments.

Example: [abaplint.jsonc](https://github.com/sbcgua/ajson/blob/master/abaplint.jsonc)

**Comment by larshp** [comment]
I'm guessing its a bit difficult, as ajson is built on top of sxml, or alternatively two passes

**Comment by sbcgua** [comment]
Yes, could be a nice feature. But indeed, SXML does not support it. 

One quick option I see is to preparse the text removing the comment by regex. And add an explicit parameter to do this (to avoid performance impact for the normal json). But it won't be 100% reliable. 
```jsonc
  "xyz": "Hello \/\/ world", // The comment with "quotes" and doubleslashes (//)
```

One more (a complex) option is to enable external parsers ... in particular I wanted to this to implement YAML or TOML parsing ... maybe ... though not anough time ... but then it also creates a possibility to alternative json parser. However this approach is in anycase way more complex

**Comment by mbtools** [comment]
I pre-parse out single-line comments. Actually, the topic goes beyond comments, as there are plenty of differences looking at full [`json5`](https://json5.org/) support. Writing this in ABAP would be bonkers and slow. The external parser (sxml or alternative) would need to support it. I don't see this happening so closing.
