### ISSUE TITLE
Taking `xstring` and `string_table` as input

### ISSUE THREAD

**Issue by mbtools** [sbcgua/ajson#189]
Currently, the JSON input must be type `string`. Ajson has to convert it to `xstring` before calling the SAP SXML class. 

If the input is already available as `xstring` (for example when getting it via abapGit `get_local/remote_files`), then it would be nice if the conversion to `string` (and back to `xstring`) could be skipped for better performance.

It would be nice to take data with type `string_table` as input as well.

I can do a PR if you like.

**Comment by sbcgua** [comment]
Interesting idea. 

whats the use case for string_table by the way ?

**Comment by mbtools** [comment]
You can get a string table 
- if you compose the `json` manually 
- get data from an editor
- have a string split by `crlf`
- as output of pre-parsing the comments

I might get to it next week.
