### ISSUE TITLE
move stringify() to ZIF_ABAPGIT_AJSON_WRITER ?

### ISSUE THREAD

**Issue by larshp** [sbcgua/ajson#37]
the ZIF_ABAPGIT_AJSON_WRITER instance cannot be used to get the actual JSON right now?

**Comment by larshp** [comment]
have to do something like this, having the interface name part of the SET method call,

```abap
    lo_ajson = zcl_abapgit_ajson=>create_empty( ).
    lo_ajson->zif_abapgit_ajson_writer~set(
      iv_path = '/'
      iv_val = <lg_tab> ).
    lo_ajson->stringify( ).
```

**Comment by larshp** [comment]
either do complete separation of reading and writing, with some methods to easily convert?

or have just one interface?

**Comment by sbcgua** [comment]
Yeah, reader and writer separation look strange for me too. It is some kind of heritage ... i think for now it should be fine to move stringify to interface and make an alias to keep compatibility

**Comment by sbcgua** [comment]
moved `stringinfy` to writer. @larshp have a look.
But really considering merging the interfaces for future - there is no clear benefit from 2 of them. reader/writer will stay for a while in any case

**Comment by larshp** [comment]
cool, do you want to keep this issue open, or a new for merging the two interfaces?

**Comment by sbcgua** [comment]
let's create a new one

**Comment by sbcgua** [comment]
opened #39
