### ISSUE TITLE
array column names are sorted

### ISSUE THREAD

**Issue by larshp** [sbcgua/ajson#38]
Hi,
Should the behavior be changed, so the json follows the ABAP structure? Or add an option to keep the columns/structure fields in the same order?

![image](https://user-images.githubusercontent.com/5888506/103454524-54459480-4ce5-11eb-9abd-a6c4836b7657.png)

![image](https://user-images.githubusercontent.com/5888506/103454528-57d91b80-4ce5-11eb-8872-4e4bf43b25ed.png)

![image](https://user-images.githubusercontent.com/5888506/103454530-60c9ed00-4ce5-11eb-87c3-354bda641a76.png)

**Comment by sbcgua** [comment]
Hmm, you mean for table serialization?

**Comment by larshp** [comment]
yes

**Comment by mbtools** [comment]
Name/value pairs in json are unordered. If you want ordered lists in json, it needs to be in an array.

**Comment by larshp** [comment]
`{"foo": 2, "bar": 1}` and `{"bar": 1, "foo": 2}` is the same in json, but when serializing ABAP structures they are ordered, and it would be easier to compare the json vs ABAP if they have the same ordering

**Comment by sbcgua** [comment]
The purpose is clear. I think it might be a parameter. But not sure how to implement it from the frst glance. 
The fields can be added freely or as a structure. And somehow the latter has to memoise the order. While the first does not need too ... hmmm. Might be crutchy... i'll think about it. Ideas also welcomed :)

**Comment by sbcgua** [comment]
Some kind of additional force_order field ...

**Comment by mbtools** [comment]
imho, it should be `{ "structure_name": [ "foo": 2, "bar": 1 ] }`. this will keep the order

**Comment by sbcgua** [comment]
So, the concept:

1) Instance flag keep_field_order (or keep_field_order_for_struc), set via `create_empty` or (maybe???) by another method `set_keep_order`
2) add a field `order` to `ty_node`.
3) on adding of a structure, if the flag is set, `convert_struc` should fill the order with sy-tabix
4) `stringify`: probably a third sorted mkey for `mt_json_tree` and key selection in `stringify_set` will do the job

**Comment by sbcgua** [comment]
@larshp should work, pls try. Docs are here: https://github.com/sbcgua/ajson#keep-item-order

**Comment by larshp** [comment]
cool, I'll try it out tomorrow

**Comment by larshp** [comment]
working, 

https://github.com/abapGit-tests/data1/pull/2/commits/441e2d0a6e809d5456b4832d9cc513827218d61b 

https://github.com/abapGit/abapGit/pull/4399

closing
