### ISSUE TITLE
Merge interfaces

### ISSUE THREAD

**Issue by sbcgua** [sbcgua/ajson#39]
create `zif_ajson` to describe all methods of the class (merge reader and writer) + `freeze` + types. The latter **can be a breaking change**.
reader and writer will stay for now

follow up from #37

**Comment by sbcgua** [comment]
@larshp will it create much mess if types will move to an interface ?

**Comment by larshp** [comment]
no, they should be in the interface for everything to work IMHO

if you are thinking about the use in abapGit, dont worry, it wont be a lot of changes, and its easy changes if any

**Comment by sbcgua** [comment]
@larshp this one is done ... should cause some changes to abapgit ...

Is it OK to close ?

**Comment by larshp** [comment]
yes 👍
