### ISSUE TITLE
more basic unit tests

### ISSUE THREAD

**Issue by larshp** [sbcgua/ajson#52]
Hi,
the parse() test, https://github.com/sbcgua/ajson/blob/master/src/zcl_ajson.clas.testclasses.abap#L122 seems to be testing a lot?

Are you open to adding more basic unit tests before this? eg. one test method for each data type

**Comment by sbcgua** [comment]
generally yes, this is better. I'm just lazy to do one-by-one :) And I reuse that mock json a couple of times so it saves time. But conceptually this is better to have separate tests.
Just one thing, this test tests types, and also depth. (Althought there is an integrational one somewhere there ...)

**Comment by larshp** [comment]
I'll just add more, more is more

**Comment by larshp** [comment]
merged, closing
