### ISSUE TITLE
Chaining for `set` methods

### ISSUE THREAD

**Issue by sbcgua** [sbcgua/ajson#66]
Maybe make all `set*` return self for chaining ?

Potential issue - `set*` are defined in `writer`, but generally we tend to move to usage of common interface. So `set*` should return zif_ajson ... beging defined in zif_ajson_writer ... maybe it is ok as a transition ...

@mbtools what do you think about it ? I have some faint memories that we discussed something like this, no ?

**Comment by mbtools** [comment]
I don't remember. One day, just rip the bandaid off and change to the single interface. It will be an easy, one-time change for the repos where reader/writer is used.

**Comment by sbcgua** [comment]
Yeap, maybe it is the way. I was also thinking about it.

@larshp do you think there will be a lot of impact on abapgit automerge process ?

**Comment by larshp** [comment]
nah, just change it, we'll see when the PR is automatically opened

if it gives errors after merge, there are errors in abaplint, which can be fixed :)

**Comment by sbcgua** [comment]
Yeah, I guess there will be no better time. Any additional usecase will just make it com complicated ... so probably this weekend ...

**Comment by sbcgua** [comment]
Thanks for the comments/opinions !

**Comment by sbcgua** [comment]
done

**Comment by sbcgua** [comment]
`v1.1.0-pre1`
