### ISSUE TITLE
Item filter

### ISSUE THREAD

**Issue by sbcgua** [sbcgua/ajson#72]
Follows https://github.com/sbcgua/ajson/issues/71#issuecomment-913987560 @larshp 

> perhaps something like adding this method to the custom mapping interface
> 
> ```abap
> methods to_json_skip_value
>   importing 
>     io_type type ref to cl_abap_typedescr
>     is_node type ty_node,
>   returning 
>     value(rv_skip) type abap_bool.
> ```
> 
> if it returns rv_skip = abap_true, then skip the value, else as normal

1) This seems to be not about skipping but about filtering, the implementation may decide to skip filled values too
2) Thus it doesn't match mapper semantics, it is a separate `filter` interface
3) Also because of performance considerations. Mapper without filter will call extra method each time and vice versa

```abap
interface zif_ajson_filter " zif_ajson_node_filter ?

  methods filter
   importing 
     io_type type ref to cl_abap_typedescr
     is_node type ty_node,
   returning 
     value(rv_KEEP) type abap_bool.
```

**Comment by larshp** [comment]
true,

`is_node` has value as a string, perhaps also pass a reference to the abap value?

**Comment by sbcgua** [comment]
NB, thoughts: typical usages to maybe implement within the package:
- filter all empty nodes
- filter out specific paths
  - maybe, makes sense to coordinate with #63 (in the long run ...)

**Comment by sbcgua** [comment]
```
push( X )
push( Y )
push( Z )
```

where Y is filtered, should result in `[X, null, Z]`, isn't it ?

**Comment by sbcgua** [comment]
... just an occasional finding ... seems that unexpectedly `ls-x = 123. append ls to tab` is faster than `append initial value to tab assigning <rec>. <rec>-x = 123.` And ... 30% faster. WTF ?

**Comment by sbcgua** [comment]
@larshp have a look at #76 
- Really draft at this moment
- children count fails
- merging ajson has a potential misuse
- and value is not transferred to the filter (e.g. to hide whole structure or table)
- a lot of code duplication...

By the way do you need io_type in the filter ? I guess not if value itself is passed ? It is no very clear what to pass therein some cases (see lo_null_type)

**Comment by larshp** [comment]
io_type: perhaps the `value` part of `is_node` is enough, but I'd like to be able to do "if value is initial then skip field", the to be able to determine if the value is initial, it requires the type of the node? but again, perhaps the json type(part of is_node) is enough

**Comment by sbcgua** [comment]
Can be closed ? Seems to be implemented by now
