### ISSUE TITLE
replace use of XFELD

### ISSUE THREAD

**Issue by larshp** [sbcgua/ajson#75]
with one of the types from https://github.com/sbcgua/ajson/pull/74

the check for XFELD will be kept in the code, but not actively unit tested, this will make the code one step closer to compatibility with Steampunk and open-abap

any thoughts?

**Comment by larshp** [comment]
note, FLAG is marked as deprecated

so either ABAP_BOOLEAN or XSDBOOLEAN

![image](https://user-images.githubusercontent.com/5888506/132825669-33cedcbd-5920-4415-9856-cad9bc81cf1b.png)

**Comment by sbcgua** [comment]
I guess the most crucial test is that at least one boolean type converts to "true"/"false" string. So as far as the type check is there I'm OK to reduce the test to abap_bool only. Or maybe change xfeld to XSDBOOLEAN (it exists in 731, but I'm not sure about 702)

@mbtools Do you have an old release to check if XSDBOOLEAN was there ?

**Comment by sbcgua** [comment]
![image](https://user-images.githubusercontent.com/15635498/132912904-89a1612d-63cb-4caa-9a6f-993d7b0d81a7.png)

![image](https://user-images.githubusercontent.com/15635498/132912947-a11b5f34-1297-4e5c-8f37-fe5c5b1f0397.png)
9 years later !

**Comment by mbtools** [comment]
702 DTEL XSD*: 

![image](https://user-images.githubusercontent.com/59966492/132931305-3c3def39-894b-488f-95bf-04aa7c6c7827.png)

XFELD exists too

**Comment by sbcgua** [comment]
Thanks !
@larshp I think it is OK to move from XFELD to XSDBOOL in UTs
